apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: multi-stage-build-go-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: multi-stage-build-go-sample
    app.kubernetes.io/part-of: multi-stage-build-go-sample
  name: multi-stage-build-go-sample
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: multi-stage-build-go-sample
status:
  loadBalancer: {}
